Neovici/cosmoz-utils

.travis.yml
README.md
wct.conf.json

Added configuration for SauceLabs testing, account "nomego" - Open Sauce (5 concurrent sessions for all repos combined)
For that reason I left Firefox latest and Chrome stable testing on Travis and only added new setups (Chrome beta, Chrome dev, Edge and Safari) through Sauce Labs.
SAUCE_USERNAME is encrypted due to some hint in guides, but realize that it's exposed through the README.md anyway for badges and browser matrix.

SauceLabs testing

---

lib/date.js
test/date.html

Frontend uses this function from cosmoz-omnitable. Considering that it's an utility function, let's give it a new home!

(minor) add toLocalISOString

---

index.js

Renamed export to `DateUtils`, marked `Date` export as deprecated; to be removed in a future major release.

(minor) `Date` export conflicts with native `Date` constructor

---

.github/workflows/workflow.yml
package-lock.json
package.json

Annotating the eslint errors and warnings to the PR is built into the setup-node task, so no need to run a separate task for this.

ci: test if setup-node problem matcher for eslint works

---

package.json

`lib/reduce/*.js` files are currently ignored

fix: adds ignored files to release

---

lib/directives/portal.js
test/directive-portal.test.js

Useful for dialogs, dropdowns, anything that needs to be rendered outside of the scope of the component, but you still want to control the content from within the component.

feat(portal): new directive for rendering parts in remote outlets

---

lib/directives/portal.js
test/directive-portal.test.js

The requestAnimationFrame solution for cleanup is not reliable, because it only catches disconnects that happen immediately after the directive is last called.
A better solution is to add a tiny helper element in the sourcePart, that does the cleanup when it is disconnected.

fix(portal): outlet part is not cleaned up

---

lib/directives/portal.js

I ran into this issue while switching views in FE.

fix(portal): outlet is not cleaned up correctly if sourcePart is destroyed quick enough

---

lib/haunted-polymer.js
test/haunted-polymer.test.js

Setting a single outputPath is very limiting, and causes unnecessary recalculations in polymer when observing subpaths of the outputPath. For example `computed: '_computeFrom(state.invoices)'` results in a new value even if state.invoices did not change, but state.otherProp did.
Migration instructions:
Drop the outputPath from the hauntedPolymer call and move it to the output of the hook:
```js
hook = () => return 'a';
hauntedPolymer('state', hook)
```
becomes
```js
hook = () => return {state: 'a'};
hauntedPolymer(hook)
```

feat(haunted-polymer): use setProperties instead of outputPath

---

lib/hooks/use-host-bounds.js
test/use-host-bounds.test.js

See https://github.com/WICG/resize-observer/issues/38 but it's a good idea anyway
to update state in a microtask or animation frame

fix(use-host-bounds): handle resizes in a frame

---

lib/money.js
test/money.test.js

In cases the object money exists but the amount itself is null. Currently this results in NaN being rendered to the user, better to render nothing instead.

fix(renderamount): adds more explicit null check on amount

---

lib/date.js

Instead of the default Date behavior which parses date only string as utc parse it as local.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#date_time_string_format

fix: parse yyyy-mm-dd as local

---

src/hooks/use-drag-items.ts

Implement a generic useDragItems hook to allow moving some html elements around.
Implement a function to a apply a from,to move to an array generating a new one.

feat(use-drag-items): initial implementation

---

src/date.ts

[AB#11539](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/11539/)
Shows time 00:40 as 00:40 instead of 24:40, some browsers shows it as 24:40 for some reason.

feat: h23 hourCycle in datetime

---

src/memoize.js
test/memoize.test.js

Useful in situations such as:
```js
api$M = useMemo(
() => memize(() => api$(path)),
[path],
),
```

feat(memoize): memize function for functions with no arguments

---

src/function.ts
src/hooks/use-property.ts

invoke did not infer the correct return type when called without arguments

feat: improve type for invoke

---

src/object.ts

Example:
```ts
const r = omit(['a', 'b'])({ a: 1, b: 2, c: 3 })
typeof r.a
//       ^? any
typeof r.b
//       ^? any
typeof r.c
//       ^? 3

fix(omit): make it properly infer when the arguments are const

---

src/promise.ts
test/promise.test.js

Useful when there is an async process that fails intermittently (e.g. an API call).

feat(promise): retry$ helper to make any function auto-retry

---

demo/keybindings.html
demo/keybindings/demo-keybindings.ts
package-lock.json
package.json
src/keybindings/README.md
src/keybindings/context.ts
src/keybindings/index.ts
src/keybindings/types.ts
src/keybindings/use-activity.ts
src/keybindings/use-keybindings.ts
src/keybindings/utils.ts

New hooks to make adding keybindings a breeze.
We use `activity` symbols to decouple the key combo from the key combo handler. Components define various activities and the app decides which keys trigger which activities.
Obligatory ASCII Venn diagram:
[ app         {          ] component }
[ key combo   { activity ]   handler }
Re [AB#14428](https://dev.azure.com/neovici/7e94365d-32b1-416f-854b-7f195da31da6/_workitems/edit/14428)
Credit goes to @megheaiulian for figuring out how to generalize https://github.com/Neovici/cosmoz-bottom-bar/pull/163

feat(keybindings): generic way of adding keybindings

---

src/keybindings/types.ts
src/keybindings/use-keybindings.ts
src/keybindings/utils.ts

Add check property function to key bindings activity handler + exclude checkbox from editable area focus check
[AB#14428](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/14428/)

fix(keybindings): add check function property and exclude checkbox from focus check

---

package-lock.json
package.json
src/memoize.ts
test/memoize.test.js

If all params are undefiend the equality checks will return true and the
function will return lastResult, which at that time will also be
undefined without calling the memoized function

fix(memoize): handle all undefined params
