Neovici/cosmoz-utils

- .editorconfig
- .eslintrc.json
- .gitignore
- .travis.yml
- cosmoz-behaviors.html
- cosmoz-datehelper-behavior.js
- cosmoz-moneyhelper-behavior.js
- cosmoz-templatehelper-behavior.js
- package-lock.json
- package.json
- polymer.json
- wct.conf.json
Add and configure lint, test, travis-ci, postinstall bower modules
> Added metadata to test, lint, auto install bower components

- .eslintrc.json
- cosmoz-datehelper-behavior.js
- cosmoz-moneyhelper-behavior.js
- demo/index.html
- package-lock.json
- package.json
- test/.eslintrc
- test/cosmoz-datehelper-behavior-test.html
- test/cosmoz-moneyhelper-behavior-test.html
- test/cosmoz-templatehelper-behavior-test.html
> Update ESLint rules

- .codeclimate.yml
- .eslintignore
- .gitignore
- .travis.yml
- cosmoz-datehelper-behavior.html
- cosmoz-moneyhelper-behavior.html
- cosmoz-templatehelper-behavior.html
- package.json
- wct.conf.json
- yarn.lock
fixes https://github.com/Neovici/cosmoz-behaviors/issues/9
> Tests code coverage and codeclimate config v2

- cosmoz-moneyhelper-behavior.html
Adding CNY and DKK currencies.
> 18621 - Adding CNY and DKK currencies

- cosmoz-moneyhelper-behavior.html
- test/cosmoz-moneyhelper-behavior-test.html
Adding amount comparison and amount identification functions, as requested in https://github.com/Neovici/cosmoz-frontend/pull/544.
> Adding amount comparison and amount identification functions

- cosmoz-datehelper-behavior.html
- test/cosmoz-datehelper-behavior-test.html
* Check for Invalid date object
* Added tests
* Fixes #20
> cosmoz-datehelper-behavior: ensureDate fix.

- wct.conf.json
Signed-off-by: Patrik Kullman <patrik.kullman@neovici.se>
> Test Firefox on Sauce Labs

- cosmoz-templatehelper-behavior.html
I want to change toFixed so it returns empty string if given bad data.
> nullcheck added, related to rm 20729

- .github/workflows/workflow.yml
- lib/money.js
- test/money.html
> fix: set locale in functions and tests

- lib/reduce/action.js
- lib/reduce/index.js
- lib/reduce/reduce.js
- test/reduce.test.js
Adds reduce and action util implementations
> feat: adds reduce implementation

- lib/hooks/use-host.js
Used to access the host element anywhere you need it.
> feat: add useHost hook

- lib/array.js
- test/array.test.js
handle strings in array helper
> fix: handle strings in array helper

- lib/array.js
- test/array.test.js
handle null in array and return []
> fix: handle null in array

- lib/hooks/use-imperative-api.js
- test/use-imperative-api.test.js
> feat(use-imperative-api): hook that exposes an imperative API on the host

- lib/date.js
Adds parseDate and inputDate helpers
> feat(date): add parseDate and inputDate helpers

- lib/function.js
- package-lock.json
- package.json
- test/money.test.js
Add `constant`, `constTrue`, `constUndefined`, `noop` functions.
Default `constTrue` for `check` attribute in `once`.
> feat(function): improve function module

- lib/promise.js
- package-lock.json
- package.json
> feat(promise): add helpers

- lib/object.js
If passed a string strProp(key) should return it.
> fix(object): strProp should handle string

- elements/cz-icon.js
- elements/cz-spinner.js
- elements/index.js
To replace polymer icons with svg icons.
> feat(icons): add svg icons

- lib/directives/spread-props.js
- test/directive-spread-props.test.js
> feat(spread-props): initialize

- src/hooks/use-notify-property.ts
Improve definition of notifyProperty & useNotifyProperty.
> feat(use-notify-property): tweak definition

- src/promise.ts
Update `ManagedPromise` type def
> feat(promise): update type def

- package-lock.json
- package.json
- src/array.ts
- src/directives/measure.ts
- src/haunted-polymer.ts
- src/hooks/use-meta.ts
- src/object.ts
- test/date.test.js
Improve the typing of `array` function.
> fix(array): add better typing

- package-lock.json
- src/array.ts
- src/function.ts
- src/object.ts
- test/function.test.js
> feat(function): add invoke helper

- package-lock.json
- package.json
- src/number.ts
- test/number.test.ts
Implement parse and round number utils.
> number: parse & round

- src/memoize.js
[Task ab#9302](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/9302/)
Moving the memoize custom function from cosmoz-omnitable to cosmoz-utils
> Fixes DevStory 9302 - link in the first comment

- test/memoize.test.js
fix: memoize is testable in cosmoz-utils - cfr [dev story 9302](https://dev.azure.com/neovici/Cosmoz3/_workitems/edit/9302/)
> Test adding 9302

- src/number.ts
> feat(number): add patterns

- package.json
- src/string.ts
- test/date.test.js
- test/string.test.ts
> feat(string): add some string utils

- src/directives/portal.ts
- src/directives/spread-props.ts
Include the param definition in directives by adding them to render
function.
> fix(directives): include params in def

- src/directives/portal.ts
> feat(portal): set content type to unknown

- src/object.ts
Allow passing almost anything to prop and strop and handling it.
> feat(prop,strProp): widen object type

- .eslintignore
- .eslintrc.json
- .github/workflows/workflow.yml
- package-lock.json
- package.json
> feat: upgrade deps

- src/array.ts
Adjust the type def of `without` helper.
> feat(array): adjust type def

- src/promise.ts
Adjust the  type def of array param of limit$ and debounce$.
> feat(promise): adjust type defs

- src/promise.ts
> feat(promise): adjust debounce type

- src/function.ts
Update the definition of `once`.
> fix: update once def

- src/function.ts
> feat: adjust once type

- src/function.ts
> fix(once): type default

- package-lock.json
- src/number.ts
- test/number.test.ts
Correct the number patterns so they don't allowed wrong chars.
> fix(number): correct pattern

- src/array.ts
Adjust `without` params typing.
> feat(array/without): adjust params typing

- src/array.ts
> feat(array): without type fallback

- src/array.ts
- test/array.test.js
> feat(array): add chunk

- src/array.ts
- test/array.test.js
> feat(array): add intersect helper

- src/directives/spread-props.ts
Adjust type of `spreadProps` directive allowing undefined.
> feat(spread-props): adjust type

- src/hooks/use-drag-items.ts
Adds `prefix` to useDragItems preventing drag and drop between different
prefixes.
> feat(use-drag-items): add prefix

- src/hooks/use-notify-property.ts
Adjust type def of use `useNotifyProperty`.
> feat(use-notify-property): adjust type

- src/hooks/use-property.ts
> feat(useProperty): implement

- src/promise.ts
> feat(promise): relax type of debounce$

- src/money.ts
Handle invalid currency in money.ts.
> fix(money): handle invalid currency

- src/promise.ts
Adjust type def promise/event$.
> feat(promise/event$): adjust type def

- src/money.ts
- test/money.test.js
Add max- and min fraction digits
Add tests
Lint test file
> feat(Money): add max- and min fraction digits

- src/index.ts
- src/sheet.ts
Helpers for pionjs component stylesheets.
> feat: sheet and css helpers

- src/directives/consume.ts
> feat(consume): adjust types of consume

- src/promise.ts
Usage:
```js
const list$ = log$((params) =>json(apiUrl('some-api', params)))
```
> feat(promise): tiny helper to make a logging version of any async function

- src/date.ts
add round up on date difference.
[Slack](https://neovici.slack.com/archives/C6LJQMJFM/p1726560505314739)
> fix(date): add round up on date difference
